# Generated by Django 5.0.7 on 2024-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrouser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='фото'),
        ),
    ]
